name: Publish Workflow
on:
  release:
    types: [published]

jobs:
  publish-redislock:
    name: publish redislock
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      - run: 'dotnet pack Kirov.RedisLock/Kirov.RedisLock.csproj --output nupkgs --configuration Release -p:PackageVersion=${{ github.ref_name }}'
        name: 'pack Kirov.RedisLock'
      - run: 'dotnet nuget add source --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/OWNER/index.json"'
      - run: 'dotnet nuget push "nupkgs/Kirov.RedisLock.${{ github.ref_name }}.nupkg" --source "github"'
        name: 'publish Kirov.RedisLock to Github'